# Mod Properties
mod_id = undertale_death_screen
mod_name = Undertale Death Screen
mod_version = 1.6.1
maven_group = com.denmoth.undertale_death_screen

# Minecraft and Loader Versions
minecraft_version = 1.21.1

# Fabric
fabric_loader_version = 0.16.5
fabric_api_version = 0.109.0+1.21.1

# NeoForge
neoforge_version = 21.1.95

# Dependencies
cloth_config_version = 15.0.140
architectury_api_version = 13.0.6

# Build properties
org.gradle.jvmargs = -Xmx3G -Dfile.encoding=UTF-8
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configuration-cache = false
architectury.common.root = true
enabled_platforms = fabric,neoforge
modmenu_version = 11.0.3
