org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.caching.debug=false

mod.github=Raik176/undertale-death-screen
mod.modrinthId=lawTOUCq
mod.modrinthSlug=undertale-death-screen
mod.curseforgeId=1161177
mod.curseforgeSlug=undertale-death-screen

mod.version=1.3.3
mod.group=com.denmoth
mod.id=undertale_death_screen
mod.name=Undertale Death Screen
mod.description=Replaces the minecraft death screen with one similar to the undertale death animation.
mod.author=Right Hand Man
mod.license=MIT

mod.mc_title=[VERSIONED]
mod.mc_targets=[VERSIONED]

deps.mixin_extras=0.5.0
deps.fabric_loader=0.17.2
deps.forge_loader=[VERSIONED]
deps.neoforge_loader=[VERSIONED]
deps.fabric_api=[VERSIONED]
deps.cloth_config=[VERSIONED]
deps.modmenu=[VERSIONED]
