# Mod Properties
mod_id = undertale_death_screen
mod_name = Undertale Death Screen: Continued
mod_version = 2.0.0
maven_group = com.denmoth.undertale_death_screen
mod_description = Makes your last heart shatter when you die just like in Undertale!
mod_author = Denmoth
mod_sources = https://github.com/Denmoth/undertale-death-screen-continued

# Minecraft and Loader Versions
minecraft_version = 1.21.5

# Fabric
fabric_loader_version = 0.16.9
fabric_api_version = 0.128.2+1.21.5

# NeoForge
neoforge_version = 21.5.97

# Dependencies
cloth_config_version = 18.0.145
architectury_api_version = 15.0.3

# Build properties
org.gradle.jvmargs = -Xmx3G -Dfile.encoding=UTF-8
org.gradle.java.home = C:/Users/Denmoth/.gradle/jdks/eclipse_adoptium-21-amd64-windows/jdk-21.0.11+10
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configuration-cache = false
architectury.common.root = true
enabled_platforms = fabric,neoforge
modmenu_version = 14.0.0
