modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://github.com/Denmoth/undertale-death-screen-continued/issues"

[[mods]]
modId = "undertale_death_screen"
version = "${version}"
displayName = "Undertale Death Screen"
authors = "Denmoth"
description = "Brings the Undertale Death Screen to Minecraft"
logoFile = "icon.png"
logoBlur = false

[[mixins]]
config = "undertale_death_screen-common.mixins.json"

[[dependencies.undertale_death_screen]]
modId = "cloth_config"
type = "optional"
mandatory = false
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"